// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPFSPyuB9DeGIT-T40OsMkeP1Tt0Xps6A',
    appId: '1:490224731202:web:0a874884beb67bff0019db',
    messagingSenderId: '490224731202',
    projectId: 'fir-authentication-5f3c5',
    authDomain: 'fir-authentication-5f3c5.firebaseapp.com',
    storageBucket: 'fir-authentication-5f3c5.firebasestorage.app',
    measurementId: 'G-98JBP83PNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe7n6D0e8SewVtb01-jvYnjrcvJDO4QbY',
    appId: '1:490224731202:android:498553fe156fdfbe0019db',
    messagingSenderId: '490224731202',
    projectId: 'fir-authentication-5f3c5',
    storageBucket: 'fir-authentication-5f3c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJiovaIQ0c4W7UAlJRfw2fd0xcv3FCugg',
    appId: '1:490224731202:ios:0ebb324e7540bb5f0019db',
    messagingSenderId: '490224731202',
    projectId: 'fir-authentication-5f3c5',
    storageBucket: 'fir-authentication-5f3c5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJiovaIQ0c4W7UAlJRfw2fd0xcv3FCugg',
    appId: '1:490224731202:ios:0ebb324e7540bb5f0019db',
    messagingSenderId: '490224731202',
    projectId: 'fir-authentication-5f3c5',
    storageBucket: 'fir-authentication-5f3c5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPFSPyuB9DeGIT-T40OsMkeP1Tt0Xps6A',
    appId: '1:490224731202:web:799203d681ad22e80019db',
    messagingSenderId: '490224731202',
    projectId: 'fir-authentication-5f3c5',
    authDomain: 'fir-authentication-5f3c5.firebaseapp.com',
    storageBucket: 'fir-authentication-5f3c5.firebasestorage.app',
    measurementId: 'G-RJF0MLS6QN',
  );
}
